/**
 * Demo fixtures for Medwise.
 *
 * Used as a fallback when NEXT_PUBLIC_SUPABASE_URL is unset or a placeholder,
 * so the app feels populated without requiring a real Supabase project.
 *
 * IMPORTANT: keep these in sync with supabase/seed.sql so the same data
 * shows up after wiring a real backend.
 */

export const isDemoMode = (): boolean => {
  const url =
    (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_SUPABASE_URL) ||
    (typeof process !== 'undefined' && process.env?.EXPO_PUBLIC_SUPABASE_URL) ||
    '';
  return !url || url.includes('placeholder') || url.includes('YOUR-');
};

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------
export const demoCategories = [
  { id: 1, slug: 'diagnostic-imaging', name: 'Diagnostic Imaging', parent_id: null, device_class: 'IIb', gmdn_term: 'Imaging system', description: null },
  { id: 2, slug: 'patient-monitoring', name: 'Patient Monitoring', parent_id: null, device_class: 'IIb', gmdn_term: 'Patient monitor', description: null },
  { id: 3, slug: 'infusion-therapy', name: 'Infusion & Therapy', parent_id: null, device_class: 'IIb', gmdn_term: 'Infusion pump', description: null },
  { id: 4, slug: 'respiratory-care', name: 'Respiratory Care', parent_id: null, device_class: 'IIb', gmdn_term: 'Ventilator', description: null },
  { id: 5, slug: 'surgical-instruments', name: 'Surgical Instruments', parent_id: null, device_class: 'IIa', gmdn_term: 'Surgical instrument', description: null },
  { id: 6, slug: 'lab-diagnostics', name: 'In-Vitro Diagnostics', parent_id: null, device_class: 'IIa', gmdn_term: 'IVD analyser', description: null },
  { id: 7, slug: 'dental', name: 'Dental Equipment', parent_id: null, device_class: 'IIa', gmdn_term: 'Dental device', description: null },
  { id: 8, slug: 'orthopedic-implants', name: 'Orthopedic Implants', parent_id: null, device_class: 'III', gmdn_term: 'Orthopedic implant', description: null },
  { id: 9, slug: 'disposables', name: 'Disposables & Consumables', parent_id: null, device_class: 'I', gmdn_term: 'Single-use device', description: null },
  { id: 10, slug: 'hospital-furniture', name: 'Hospital Furniture', parent_id: null, device_class: 'I', gmdn_term: 'Hospital bed', description: null },
  { id: 11, slug: 'sterilization', name: 'Sterilization & Disinfection', parent_id: null, device_class: 'IIa', gmdn_term: 'Sterilizer', description: null },
  { id: 12, slug: 'ophthalmic', name: 'Ophthalmic Devices', parent_id: null, device_class: 'IIa', gmdn_term: 'Ophthalmic device', description: null },
];

// ---------------------------------------------------------------------------
// Suppliers (Chinese medtech manufacturers)
// ---------------------------------------------------------------------------
export const demoSuppliers = [
  {
    id: 'sup-mindray',
    kind: 'supplier' as const,
    legal_name: 'Shenzhen Mindray Bio-Medical Electronics Co., Ltd. (Demo)',
    display_name: 'Mindray',
    country: 'CN' as const,
    website: 'https://www.mindray.com',
    about: 'Founded 1991, Shenzhen. Top-3 Chinese medtech OEM. Patient monitoring, anaesthesia, IVD, ultrasound. Exports to 190+ countries; NMPA + CE + FDA 510(k) on most product lines.',
    verified: true,
    verified_at: '2024-08-15T00:00:00Z',
    created_at: '2024-08-15T00:00:00Z',
    updated_at: '2024-08-15T00:00:00Z',
  },
  {
    id: 'sup-edan',
    kind: 'supplier' as const,
    legal_name: 'EDAN Instruments, Inc. (Demo)',
    display_name: 'Edan',
    country: 'CN' as const,
    website: 'https://www.edan.com',
    about: 'Founded 1995, Shenzhen. Specializes in ECG, ultrasound, OB/GYN, and IVD analyzers. CDSCO-listed importer relationships across India.',
    verified: true,
    verified_at: '2024-09-02T00:00:00Z',
    created_at: '2024-09-02T00:00:00Z',
    updated_at: '2024-09-02T00:00:00Z',
  },
  {
    id: 'sup-sonoscape',
    kind: 'supplier' as const,
    legal_name: 'SonoScape Medical Corp. (Demo)',
    display_name: 'SonoScape',
    country: 'CN' as const,
    website: 'https://www.sonoscape.com',
    about: 'Shenzhen-based imaging specialist. Portable & console ultrasound, endoscopy. Known for value-positioned ultrasound for tier-2 hospitals.',
    verified: true,
    verified_at: '2024-10-10T00:00:00Z',
    created_at: '2024-10-10T00:00:00Z',
    updated_at: '2024-10-10T00:00:00Z',
  },
  {
    id: 'sup-yuyue',
    kind: 'supplier' as const,
    legal_name: 'Jiangsu Yuyue Medical Equipment & Supply Co., Ltd. (Demo)',
    display_name: 'Yuyue',
    country: 'CN' as const,
    website: 'https://www.yuwell.com',
    about: 'Founded 1998, Jiangsu. Home medical (O2 concentrators, nebulizers, beds, wheelchairs), sterilization. Strong cost position on volume SKUs.',
    verified: true,
    verified_at: '2024-07-20T00:00:00Z',
    created_at: '2024-07-20T00:00:00Z',
    updated_at: '2024-07-20T00:00:00Z',
  },
  {
    id: 'sup-comen',
    kind: 'supplier' as const,
    legal_name: 'Shenzhen Comen Medical Instruments Co., Ltd. (Demo)',
    display_name: 'Comen',
    country: 'CN' as const,
    website: 'https://www.comenchina.com',
    about: 'Patient monitoring, defibrillators, ECG, infusion. Mid-tier OEM with strong customization service for distributors.',
    verified: true,
    verified_at: '2024-11-01T00:00:00Z',
    created_at: '2024-11-01T00:00:00Z',
    updated_at: '2024-11-01T00:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Buyers (Indian healthcare orgs)
// ---------------------------------------------------------------------------
export const demoBuyers = [
  {
    id: 'buy-apollo',
    kind: 'buyer' as const,
    legal_name: 'Apollo Hospitals Enterprise Limited (Demo)',
    display_name: 'Apollo Hospitals',
    country: 'IN' as const,
    website: 'https://www.apollohospitals.com',
    about: 'Multi-specialty hospital chain. 71+ hospitals across India.',
    verified: true,
    verified_at: '2024-09-01T00:00:00Z',
    created_at: '2024-09-01T00:00:00Z',
    updated_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'buy-fortis',
    kind: 'buyer' as const,
    legal_name: 'Fortis Healthcare Limited (Demo)',
    display_name: 'Fortis Healthcare',
    country: 'IN' as const,
    website: 'https://www.fortishealthcare.com',
    about: 'Multi-specialty hospital chain. 36 hospitals.',
    verified: true,
    verified_at: '2024-09-15T00:00:00Z',
    created_at: '2024-09-15T00:00:00Z',
    updated_at: '2024-09-15T00:00:00Z',
  },
  {
    id: 'buy-manipal',
    kind: 'buyer' as const,
    legal_name: 'Manipal Health Enterprises Pvt. Ltd. (Demo)',
    display_name: 'Manipal Hospitals',
    country: 'IN' as const,
    website: 'https://www.manipalhospitals.com',
    about: 'Bengaluru-headquartered multi-specialty chain.',
    verified: true,
    verified_at: '2024-10-05T00:00:00Z',
    created_at: '2024-10-05T00:00:00Z',
    updated_at: '2024-10-05T00:00:00Z',
  },
  {
    id: 'buy-medplus',
    kind: 'buyer' as const,
    legal_name: 'MedPlus Health Services Ltd. (Demo)',
    display_name: 'MedPlus Distributors',
    country: 'IN' as const,
    website: 'https://www.medplusmart.com',
    about: 'Distributor + pharmacy chain, Hyderabad-headquartered.',
    verified: false,
    verified_at: null,
    created_at: '2025-02-12T00:00:00Z',
    updated_at: '2025-02-12T00:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Products
// ---------------------------------------------------------------------------
const product = (p: any) => ({
  active: true,
  images: [],
  warranty_months: 24,
  created_at: '2025-01-15T00:00:00Z',
  updated_at: '2025-01-15T00:00:00Z',
  lead_time_days_express: null,
  ...p,
});

export const demoProducts = [
  // ---- Patient Monitoring ----
  product({
    id: 'p-pm-1',
    supplier_org_id: 'sup-mindray',
    category_id: 2,
    sku: 'MR-PM-12',
    name: '12.1" Multi-Parameter Patient Monitor (5-para)',
    short_description: 'ECG, SpO2, NIBP, Temp, Resp on a 12.1" touchscreen. ICU/ward grade.',
    long_description: 'Bedside monitor with 5 standard parameters, optional CO2/IBP modules, 72h trend storage, central station compatibility (LAN + WiFi), and 4h internal battery. CDSCO-cleared, NMPA + CE on file.',
    device_class: 'IIb',
    hs_code: '9018.19',
    gmdn_code: '35119',
    specs: { 'Screen': '12.1" touchscreen', 'Parameters': 'ECG, SpO2, NIBP, Temp, Resp', 'Battery': '4 hours', 'Network': 'LAN + WiFi' },
    moq: 10,
    unit_price_usd: 850,
    lead_time_days: 28,
    lead_time_days_express: 18,
  }),
  product({
    id: 'p-pm-2',
    supplier_org_id: 'sup-mindray',
    category_id: 2,
    sku: 'MR-PM-15',
    name: '15" ICU Patient Monitor (8-para)',
    short_description: 'ICU-grade 8-parameter monitor with IBP, CO2, Cardiac Output.',
    long_description: 'High-acuity bedside monitor for ICU/OT. ECG (12-lead), SpO2, NIBP, Temp×2, Resp, IBP×2, CO2 (sidestream + mainstream options), Cardiac Output. EMR integration via HL7.',
    device_class: 'IIb',
    hs_code: '9018.19',
    gmdn_code: '35119',
    specs: { 'Screen': '15" capacitive touch', 'Parameters': '8-para (ICU)', 'EMR': 'HL7 / DICOM-MWL' },
    moq: 5,
    unit_price_usd: 1800,
    lead_time_days: 35,
  }),
  product({
    id: 'p-pm-3',
    supplier_org_id: 'sup-edan',
    category_id: 2,
    sku: 'ED-PM-7',
    name: 'Portable Patient Monitor 7"',
    short_description: 'Lightweight 7" monitor for transport, ER, emergency response.',
    long_description: '7" sunlight-readable display, 6-hour battery, hot-swappable, drop-resistant. Includes carry strap and 12V vehicle adapter. Popular for ambulance fleets.',
    device_class: 'IIb',
    specs: { 'Screen': '7" sunlight-readable', 'Battery': '6 hours hot-swap', 'Weight': '2.1 kg' },
    moq: 20,
    unit_price_usd: 620,
    lead_time_days: 21,
  }),
  product({
    id: 'p-pm-4',
    supplier_org_id: 'sup-comen',
    category_id: 2,
    sku: 'CM-CMS-16',
    name: 'Central Monitoring Station (16-bed)',
    short_description: 'View 16 patient monitors from one station. ICU and CCU.',
    long_description: 'Centralized monitoring for up to 16 beds. Trends, alarms, full-disclosure 72h waveform storage, arrhythmia review. Standard Mindray/Edan/Comen monitor compatibility.',
    device_class: 'IIb',
    specs: { 'Beds': 16, 'Storage': '72h full-disclosure', 'Arrhythmia review': 'Yes' },
    moq: 1,
    unit_price_usd: 4200,
    lead_time_days: 45,
  }),
  product({
    id: 'p-pm-5',
    supplier_org_id: 'sup-edan',
    category_id: 2,
    sku: 'ED-ECG-12',
    name: '12-Lead Resting ECG with Interpretation',
    short_description: 'Diagnostic 12-lead ECG with auto-interpretation, thermal print, PDF export.',
    long_description: 'Touchscreen 12-lead ECG with University of Glasgow interpretation algorithm. Thermal printer, USB/LAN export, optional WiFi.',
    device_class: 'IIa',
    specs: { 'Leads': 12, 'Interpretation': 'UoG algorithm', 'Print': 'Thermal A4' },
    moq: 10,
    unit_price_usd: 1100,
    lead_time_days: 25,
  }),

  // ---- Infusion ----
  product({
    id: 'p-ip-1',
    supplier_org_id: 'sup-mindray',
    category_id: 3,
    sku: 'MR-IP-1',
    name: 'Volumetric Infusion Pump (single channel)',
    short_description: '0.1–1500 mL/h, drug library, CDSCO + CE.',
    long_description: 'Single-channel volumetric pump with drug library (200+ drugs), KVO, anti-bolus protection, 4h internal battery, alarm log. CDSCO Import + CE + NMPA on file.',
    device_class: 'IIb',
    specs: { 'Rate range': '0.1–1500 mL/h', 'Drug library': '200+ drugs', 'Battery': '4 hours' },
    moq: 20,
    unit_price_usd: 380,
    lead_time_days: 21,
    lead_time_days_express: 12,
  }),
  product({
    id: 'p-ip-2',
    supplier_org_id: 'sup-mindray',
    category_id: 3,
    sku: 'MR-SP-2',
    name: 'Syringe Pump (dual channel)',
    short_description: 'Dual-channel syringe pump with TCI, drug library.',
    long_description: 'Dual-channel syringe pump compatible with 5/10/20/50ml syringes from 7 brands. TCI mode, drug library, occlusion detection.',
    device_class: 'IIb',
    specs: { 'Channels': 2, 'Syringe sizes': '5/10/20/50 ml', 'TCI': 'Yes' },
    moq: 15,
    unit_price_usd: 560,
    lead_time_days: 24,
  }),

  // ---- Respiratory ----
  product({
    id: 'p-oc-5',
    supplier_org_id: 'sup-yuyue',
    category_id: 4,
    sku: 'YY-OC-5',
    name: '5L Oxygen Concentrator',
    short_description: '5 L/min continuous flow, ≥93% purity, low-noise (<45 dB).',
    long_description: 'Home + clinic use. Continuous flow 5 L/min, OPI alarm, hour meter, optional nebulizer outlet. Suitable for COPD, post-operative recovery.',
    device_class: 'IIa',
    specs: { 'Flow': '5 L/min', 'Purity': '≥93%', 'Noise': '<45 dB' },
    moq: 30,
    unit_price_usd: 220,
    lead_time_days: 18,
    lead_time_days_express: 10,
  }),
  product({
    id: 'p-oc-10',
    supplier_org_id: 'sup-yuyue',
    category_id: 4,
    sku: 'YY-OC-10',
    name: '10L Oxygen Concentrator',
    short_description: '10 L/min for high-flow therapy and dual-patient use.',
    long_description: 'Higher-capacity concentrator for high-flow therapy or splitting between two patients. Dual outlet, low-pressure alarm.',
    device_class: 'IIa',
    specs: { 'Flow': '10 L/min', 'Purity': '≥93%', 'Outlets': 2 },
    moq: 15,
    unit_price_usd: 380,
    lead_time_days: 21,
  }),
  product({
    id: 'p-vent-icu',
    supplier_org_id: 'sup-mindray',
    category_id: 4,
    sku: 'MR-VENT-ICU',
    name: 'ICU Ventilator',
    short_description: 'Invasive + non-invasive modes, neonate–adult, full ICU suite.',
    long_description: 'ICU ventilator covering VC, PC, SIMV, PSV, CPAP, NIV. Patient range neonate to adult. Built-in compressor, hot-swap battery, 15" touchscreen, ASV mode.',
    device_class: 'IIb',
    specs: { 'Modes': 'VC, PC, SIMV, PSV, CPAP, NIV, ASV', 'Range': 'Neonate – Adult', 'Battery': 'Hot-swap' },
    moq: 1,
    unit_price_usd: 8500,
    lead_time_days: 45,
  }),
  product({
    id: 'p-bipap',
    supplier_org_id: 'sup-comen',
    category_id: 4,
    sku: 'CM-BIPAP-A',
    name: 'BiPAP Auto',
    short_description: 'Auto-titrating BiPAP for OSA + COPD overlap.',
    long_description: 'BiPAP with auto pressure adjustment, integrated humidifier, heated tube, SD card data logging compatible with ResMed/Philips data formats.',
    device_class: 'IIa',
    specs: { 'Mode': 'Auto BiPAP', 'Humidifier': 'Integrated heated', 'Data': 'SD card + USB' },
    moq: 10,
    unit_price_usd: 720,
    lead_time_days: 28,
  }),

  // ---- Imaging ----
  product({
    id: 'p-us-port',
    supplier_org_id: 'sup-sonoscape',
    category_id: 1,
    sku: 'SS-US-12P',
    name: 'Portable Ultrasound 12"',
    short_description: 'Color Doppler portable ultrasound with 3 probe ports.',
    long_description: '12" touch display, color Doppler, harmonic imaging, 3 probe ports (convex/linear/phased). DICOM 3.0, 4h battery. Trolley optional.',
    device_class: 'IIb',
    specs: { 'Probes': '3 ports', 'Doppler': 'Color, PW, CW', 'DICOM': '3.0' },
    moq: 2,
    unit_price_usd: 4800,
    lead_time_days: 35,
  }),
  product({
    id: 'p-us-cons',
    supplier_org_id: 'sup-sonoscape',
    category_id: 1,
    sku: 'SS-US-CON',
    name: 'Console Ultrasound + 3 probes',
    short_description: 'Floor-standing console with convex, linear, transvaginal probes included.',
    long_description: 'High-end console ultrasound bundled with 3 probes. Elastography, 4D OB optional. Two large rotating displays. CDSCO-cleared.',
    device_class: 'IIb',
    specs: { 'Probes included': 'C5-2, L12-4, V8-4', 'Elastography': 'Yes', 'OB': '4D optional' },
    moq: 1,
    unit_price_usd: 18500,
    lead_time_days: 60,
  }),

  // ---- Surgical ----
  product({
    id: 'p-esu',
    supplier_org_id: 'sup-comen',
    category_id: 5,
    sku: 'CM-ESU-300',
    name: 'Electrosurgical Unit (300W)',
    short_description: '300W ESU with cut/coag, argon-compatible, monopolar + bipolar.',
    long_description: 'Mid-range ESU suitable for general surgery, OB/GYN, urology. 8 cut modes + 8 coag modes, argon-ready, return-electrode monitoring.',
    device_class: 'IIb',
    specs: { 'Power': '300 W', 'Modes': 'Mono + Bipolar', 'Argon': 'Compatible' },
    moq: 3,
    unit_price_usd: 1200,
    lead_time_days: 28,
  }),

  // ---- Lab ----
  product({
    id: 'p-hema-5p',
    supplier_org_id: 'sup-mindray',
    category_id: 6,
    sku: 'MR-HEMA-5',
    name: '5-Part Hematology Analyzer',
    short_description: '60 samples/h, 5-part diff, autoloader, reticulocyte mode.',
    long_description: 'Automated 5-part differential CBC analyzer. 60 samples/hour, 25 parameters + 3 histograms. Optional reticulocyte module. CDSCO + NMPA + CE.',
    device_class: 'IIa',
    specs: { 'Throughput': '60/hour', 'Differential': '5-part', 'Reticulocyte': 'Optional' },
    moq: 1,
    unit_price_usd: 12000,
    lead_time_days: 45,
  }),
  product({
    id: 'p-biochem',
    supplier_org_id: 'sup-edan',
    category_id: 6,
    sku: 'ED-BC-200',
    name: 'Semi-Auto Biochemistry Analyzer',
    short_description: '200 tests/h, open reagent system, peristaltic flow.',
    long_description: 'Semi-auto biochemistry analyzer accepting open and closed reagents. 200 tests/hour, 8 wavelengths, integrated peristaltic flow cell.',
    device_class: 'IIa',
    specs: { 'Throughput': '200/hour', 'Reagents': 'Open + closed', 'Wavelengths': 8 },
    moq: 2,
    unit_price_usd: 3800,
    lead_time_days: 35,
  }),

  // ---- Dental ----
  product({
    id: 'p-dental-chair',
    supplier_org_id: 'sup-yuyue',
    category_id: 7,
    sku: 'YY-DC-200',
    name: 'Dental Chair (top-mount)',
    short_description: 'Top-mount dental chair with LED light, 3-way syringe, scaler.',
    long_description: 'Complete dental chair set including LED operatory light, 3-way syringe, ultrasonic scaler, suction, spittoon. Programmable memory positions.',
    device_class: 'IIa',
    specs: { 'Mount': 'Top-mount', 'Light': 'LED operatory', 'Memory positions': 4 },
    moq: 1,
    unit_price_usd: 1800,
    lead_time_days: 35,
  }),

  // ---- Disposables ----
  product({
    id: 'p-mask',
    supplier_org_id: 'sup-yuyue',
    category_id: 9,
    sku: 'YY-MASK-50',
    name: 'Disposable 3-ply Surgical Mask (box of 50)',
    short_description: 'BFE ≥98%, Type IIR. CE + NMPA + CDSCO-listed.',
    long_description: 'Type IIR surgical masks, BFE ≥98%, fluid-resistant. Box of 50. Pallet pricing available.',
    device_class: 'I',
    specs: { 'Type': 'IIR', 'BFE': '≥98%', 'Per box': 50 },
    moq: 500,
    unit_price_usd: 4.5,
    lead_time_days: 7,
  }),
  product({
    id: 'p-gloves',
    supplier_org_id: 'sup-yuyue',
    category_id: 9,
    sku: 'YY-GLV-N100',
    name: 'Examination Gloves Nitrile (box of 100)',
    short_description: 'Powder-free nitrile, AQL 1.5, sizes XS–XL.',
    long_description: 'Single-use nitrile examination gloves, powder-free, latex-free. AQL 1.5. Available in XS, S, M, L, XL.',
    device_class: 'I',
    specs: { 'Material': 'Nitrile', 'AQL': '1.5', 'Per box': 100 },
    moq: 1000,
    unit_price_usd: 7.2,
    lead_time_days: 7,
  }),

  // ---- Hospital furniture ----
  product({
    id: 'p-icu-bed',
    supplier_org_id: 'sup-yuyue',
    category_id: 10,
    sku: 'YY-BED-ICU5',
    name: 'ICU Electric Bed (5-function)',
    short_description: 'Electric ICU bed with CPR, Trendelenburg, height, head, foot.',
    long_description: '5-function ICU electric bed (head, foot, height, Trendelenburg, reverse Trendelenburg). Battery backup, X-ray translucent backrest, IV pole + drainage hooks.',
    device_class: 'I',
    specs: { 'Functions': 5, 'X-ray translucent': 'Backrest', 'Battery backup': 'Yes' },
    moq: 5,
    unit_price_usd: 1200,
    lead_time_days: 35,
  }),

  // ---- Sterilization ----
  product({
    id: 'p-autoclave-24',
    supplier_org_id: 'sup-yuyue',
    category_id: 11,
    sku: 'YY-AC-24',
    name: 'Autoclave Steam Sterilizer 24L',
    short_description: 'Class B 24L autoclave with B&D test, vacuum cycles.',
    long_description: 'Class B 24L benchtop autoclave with vacuum cycles (pre + post), Bowie & Dick test, USB log export. Suited for clinics and small OTs.',
    device_class: 'IIa',
    specs: { 'Volume': '24 L', 'Class': 'B', 'Vacuum': 'Pre + post' },
    moq: 2,
    unit_price_usd: 850,
    lead_time_days: 28,
  }),

  // ---- Ophthalmic ----
  product({
    id: 'p-slit-lamp',
    supplier_org_id: 'sup-edan',
    category_id: 12,
    sku: 'ED-SL-100',
    name: 'Slit Lamp with Imaging',
    short_description: 'Tabletop slit lamp with HD camera and patient archive software.',
    long_description: 'Slit lamp biomicroscope with integrated 5MP HD camera, beamsplitter, and PC-based image archiving. Suitable for OPD ophthalmology.',
    device_class: 'IIa',
    specs: { 'Magnification': '6x/10x/16x/25x', 'Camera': '5MP HD', 'Archive': 'PC software' },
    moq: 2,
    unit_price_usd: 1800,
    lead_time_days: 35,
  }),
];

// ---------------------------------------------------------------------------
// Compose products with joined supplier + category for query results
// ---------------------------------------------------------------------------
export const demoProductsWithRelations = demoProducts.map((p) => ({
  ...p,
  supplier: demoSuppliers.find((s) => s.id === p.supplier_org_id),
  category: demoCategories.find((c) => c.id === p.category_id),
  certifications: getProductCerts(p.id),
}));

function getProductCerts(productId: string) {
  const certPlan: Record<string, Array<{ kind: string; cert_number: string; expires_on: string }>> = {
    'p-pm-1': [
      { kind: 'NMPA', cert_number: 'NMPA-PM-2024-001', expires_on: '2028-12-31' },
      { kind: 'CE', cert_number: 'CE-PM-2023-001', expires_on: '2027-06-30' },
      { kind: 'CDSCO_IMPORT', cert_number: 'CDSCO-PM-2024-001', expires_on: '2027-12-31' },
      { kind: 'FDA_510K', cert_number: 'K201234', expires_on: '2030-01-01' },
    ],
    'p-pm-2': [
      { kind: 'NMPA', cert_number: 'NMPA-PM-2024-002', expires_on: '2028-12-31' },
      { kind: 'CE', cert_number: 'CE-PM-2023-002', expires_on: '2027-06-30' },
      { kind: 'CDSCO_IMPORT', cert_number: 'CDSCO-PM-2024-002', expires_on: '2027-12-31' },
    ],
    'p-ip-1': [
      { kind: 'NMPA', cert_number: 'NMPA-IP-2024-001', expires_on: '2028-12-31' },
      { kind: 'CE', cert_number: 'CE-IP-2023-001', expires_on: '2027-06-30' },
      { kind: 'CDSCO_IMPORT', cert_number: 'CDSCO-IP-2024-001', expires_on: '2027-12-31' },
    ],
    'p-vent-icu': [
      { kind: 'NMPA', cert_number: 'NMPA-VT-2024-001', expires_on: '2028-12-31' },
      { kind: 'CE', cert_number: 'CE-VT-2023-001', expires_on: '2027-06-30' },
      { kind: 'CDSCO_IMPORT', cert_number: 'CDSCO-VT-2024-001', expires_on: '2027-12-31' },
      { kind: 'MDSAP', cert_number: 'MDSAP-2024-A1', expires_on: '2027-09-30' },
    ],
    'p-us-cons': [
      { kind: 'NMPA', cert_number: 'NMPA-US-2024-001', expires_on: '2028-12-31' },
      { kind: 'CE', cert_number: 'CE-US-2023-001', expires_on: '2027-06-30' },
      { kind: 'CDSCO_IMPORT', cert_number: 'CDSCO-US-2024-001', expires_on: '2027-12-31' },
    ],
  };
  return (certPlan[productId] ?? []).map((c, i) => ({
    id: `${productId}-cert-${i}`,
    product_id: productId,
    ...c,
  }));
}

// ---------------------------------------------------------------------------
// Orders + shipments (varied statuses for tracking demo)
// ---------------------------------------------------------------------------
export const demoOrders = [
  {
    id: 'ord-1',
    order_no: 'MW-2026-000001',
    buyer_org_id: 'buy-apollo',
    supplier_org_id: 'sup-mindray',
    rfq_response_id: null,
    product_id: 'p-pm-1',
    quantity: 50,
    unit_price_usd: 820,
    total_usd: 41000,
    incoterm: 'CIF',
    status: 'in_transit' as const,
    promised_dispatch_on: '2026-05-10',
    promised_delivery_on: '2026-06-05',
    actual_dispatch_on: '2026-05-10',
    actual_delivery_on: null,
    created_at: '2026-04-15T08:00:00Z',
    updated_at: '2026-05-17T11:00:00Z',
  },
  {
    id: 'ord-2',
    order_no: 'MW-2026-000002',
    buyer_org_id: 'buy-fortis',
    supplier_org_id: 'sup-mindray',
    rfq_response_id: null,
    product_id: 'p-vent-icu',
    quantity: 8,
    unit_price_usd: 8100,
    total_usd: 64800,
    incoterm: 'DDP',
    status: 'in_production' as const,
    promised_dispatch_on: '2026-06-20',
    promised_delivery_on: '2026-07-22',
    actual_dispatch_on: null,
    actual_delivery_on: null,
    created_at: '2026-05-02T08:00:00Z',
    updated_at: '2026-05-25T14:00:00Z',
  },
  {
    id: 'ord-3',
    order_no: 'MW-2026-000003',
    buyer_org_id: 'buy-manipal',
    supplier_org_id: 'sup-sonoscape',
    rfq_response_id: null,
    product_id: 'p-us-port',
    quantity: 4,
    unit_price_usd: 4650,
    total_usd: 18600,
    incoterm: 'FOB',
    status: 'shipped' as const,
    promised_dispatch_on: '2026-05-20',
    promised_delivery_on: '2026-06-18',
    actual_dispatch_on: '2026-05-22',
    actual_delivery_on: null,
    created_at: '2026-04-25T08:00:00Z',
    updated_at: '2026-05-22T15:00:00Z',
  },
  {
    id: 'ord-4',
    order_no: 'MW-2026-000004',
    buyer_org_id: 'buy-apollo',
    supplier_org_id: 'sup-yuyue',
    rfq_response_id: null,
    product_id: 'p-oc-5',
    quantity: 120,
    unit_price_usd: 205,
    total_usd: 24600,
    incoterm: 'CIF',
    status: 'delivered' as const,
    promised_dispatch_on: '2026-03-15',
    promised_delivery_on: '2026-04-12',
    actual_dispatch_on: '2026-03-14',
    actual_delivery_on: '2026-04-08',
    created_at: '2026-02-20T08:00:00Z',
    updated_at: '2026-04-08T16:00:00Z',
  },
  {
    id: 'ord-5',
    order_no: 'MW-2026-000005',
    buyer_org_id: 'buy-medplus',
    supplier_org_id: 'sup-yuyue',
    rfq_response_id: null,
    product_id: 'p-mask',
    quantity: 2000,
    unit_price_usd: 4.2,
    total_usd: 8400,
    incoterm: 'FOB',
    status: 'qc' as const,
    promised_dispatch_on: '2026-05-30',
    promised_delivery_on: '2026-06-12',
    actual_dispatch_on: null,
    actual_delivery_on: null,
    created_at: '2026-05-20T08:00:00Z',
    updated_at: '2026-05-27T10:00:00Z',
  },
  {
    id: 'ord-6',
    order_no: 'MW-2026-000006',
    buyer_org_id: 'buy-fortis',
    supplier_org_id: 'sup-edan',
    rfq_response_id: null,
    product_id: 'p-biochem',
    quantity: 6,
    unit_price_usd: 3650,
    total_usd: 21900,
    incoterm: 'CIF',
    status: 'pending_payment' as const,
    promised_dispatch_on: '2026-07-05',
    promised_delivery_on: '2026-08-02',
    actual_dispatch_on: null,
    actual_delivery_on: null,
    created_at: '2026-05-28T08:00:00Z',
    updated_at: '2026-05-28T08:00:00Z',
  },
];

export const demoShipments: Record<string, any> = {
  'ord-1': {
    id: 'ship-1',
    order_id: 'ord-1',
    carrier: 'COSCO',
    tracking_no: 'COSU6789012345',
    mode: 'sea_fcl' as const,
    origin_port: 'Yantian (Shenzhen)',
    destination_port: 'Nhava Sheva (Mumbai)',
    dispatched_at: '2026-05-10T08:00:00Z',
    eta: '2026-06-05T16:00:00Z',
    delivered_at: null,
    current_location: 'Singapore Strait',
    current_status: 'In transit',
  },
  'ord-3': {
    id: 'ship-3',
    order_id: 'ord-3',
    carrier: 'DHL',
    tracking_no: 'DHL1234567890',
    mode: 'air' as const,
    origin_port: 'Shenzhen Airport',
    destination_port: 'Bengaluru Kempegowda',
    dispatched_at: '2026-05-22T15:00:00Z',
    eta: '2026-05-29T10:00:00Z',
    delivered_at: null,
    current_location: 'Hong Kong Hub',
    current_status: 'Departed origin facility',
  },
  'ord-4': {
    id: 'ship-4',
    order_id: 'ord-4',
    carrier: 'Maersk',
    tracking_no: 'MAEU9876543210',
    mode: 'sea_lcl' as const,
    origin_port: 'Shanghai',
    destination_port: 'Chennai',
    dispatched_at: '2026-03-14T08:00:00Z',
    eta: '2026-04-12T08:00:00Z',
    delivered_at: '2026-04-08T16:00:00Z',
    current_location: 'Apollo Chennai warehouse',
    current_status: 'Delivered',
  },
};

export const demoShipmentEvents: Record<string, any[]> = {
  'ship-1': [
    { id: 1, shipment_id: 'ship-1', occurred_at: '2026-05-09T03:00:00Z', location: 'Shenzhen factory', status: 'Picked up', description: 'Container sealed and dispatched to port', source: 'manual_supplier', created_at: '2026-05-09T03:00:00Z' },
    { id: 2, shipment_id: 'ship-1', occurred_at: '2026-05-10T08:00:00Z', location: 'Yantian Port', status: 'Loaded on vessel', description: 'Loaded on COSCO BANGKOK V.0123W', source: 'carrier_webhook', created_at: '2026-05-10T08:00:00Z' },
    { id: 3, shipment_id: 'ship-1', occurred_at: '2026-05-17T11:00:00Z', location: 'Singapore Strait', status: 'In transit', description: 'Vessel passed Singapore Strait', source: 'carrier_webhook', created_at: '2026-05-17T11:00:00Z' },
  ],
  'ship-3': [
    { id: 10, shipment_id: 'ship-3', occurred_at: '2026-05-22T14:00:00Z', location: 'Shenzhen factory', status: 'Picked up', description: 'Packaged in 2 crates, 145 kg total', source: 'manual_supplier', created_at: '2026-05-22T14:00:00Z' },
    { id: 11, shipment_id: 'ship-3', occurred_at: '2026-05-22T20:30:00Z', location: 'Shenzhen Airport (SZX)', status: 'Departed origin facility', description: 'On flight DHL CN8821', source: 'carrier_webhook', created_at: '2026-05-22T20:30:00Z' },
    { id: 12, shipment_id: 'ship-3', occurred_at: '2026-05-23T02:15:00Z', location: 'Hong Kong Hub', status: 'Arrived at hub', description: 'Transfer scan', source: 'carrier_webhook', created_at: '2026-05-23T02:15:00Z' },
  ],
  'ship-4': [
    { id: 20, shipment_id: 'ship-4', occurred_at: '2026-03-13T10:00:00Z', location: 'Shanghai factory', status: 'Picked up', source: 'manual_supplier', description: null, created_at: '2026-03-13T10:00:00Z' },
    { id: 21, shipment_id: 'ship-4', occurred_at: '2026-03-14T08:00:00Z', location: 'Shanghai Port', status: 'Loaded on vessel', source: 'carrier_webhook', description: null, created_at: '2026-03-14T08:00:00Z' },
    { id: 22, shipment_id: 'ship-4', occurred_at: '2026-04-04T06:00:00Z', location: 'Chennai Port', status: 'Arrived at destination', source: 'carrier_webhook', description: null, created_at: '2026-04-04T06:00:00Z' },
    { id: 23, shipment_id: 'ship-4', occurred_at: '2026-04-07T14:00:00Z', location: 'Chennai Customs', status: 'Customs cleared', description: 'Bill of entry filed under HS 9019.20', source: 'carrier_webhook', created_at: '2026-04-07T14:00:00Z' },
    { id: 24, shipment_id: 'ship-4', occurred_at: '2026-04-08T16:00:00Z', location: 'Apollo Chennai warehouse', status: 'Delivered', description: 'Signed by P. Krishnan, Stores', source: 'manual_buyer', created_at: '2026-04-08T16:00:00Z' },
  ],
};

// ---------------------------------------------------------------------------
// RFQs (open requirements buyers have posted)
// ---------------------------------------------------------------------------
export const demoRfqs = [
  {
    id: 'rfq-1',
    buyer_org_id: 'buy-apollo',
    created_by: 'demo-user-1',
    title: '20× ICU ventilators for Chennai Speciality Hospital expansion',
    category_id: 4,
    description: 'Need 20 ICU ventilators for the new 80-bed ICU block opening Q3. Must support neonate to adult, NIV mode required. CDSCO Import + NMPA mandatory. Site survey + on-site training expected.',
    target_specs: {},
    quantity: 20,
    target_unit_price_usd: 7500,
    required_lead_time_days: 60,
    required_certifications: ['CDSCO_IMPORT', 'NMPA', 'CE'],
    incoterm: 'CIF',
    delivery_port: 'Chennai',
    closes_at: '2026-06-15T00:00:00Z',
    status: 'open' as const,
    created_at: '2026-05-20T08:00:00Z',
  },
  {
    id: 'rfq-2',
    buyer_org_id: 'buy-fortis',
    created_by: 'demo-user-2',
    title: '100× 5L oxygen concentrators for OPD network',
    category_id: 4,
    description: 'Bulk procurement for OPD respiratory therapy. 100 units of 5L concentrators, 2-year warranty minimum, India service network required.',
    target_specs: {},
    quantity: 100,
    target_unit_price_usd: 200,
    required_lead_time_days: 30,
    required_certifications: ['CDSCO_IMPORT'],
    incoterm: 'DDP',
    delivery_port: 'Delhi',
    closes_at: '2026-06-10T00:00:00Z',
    status: 'open' as const,
    created_at: '2026-05-22T08:00:00Z',
  },
  {
    id: 'rfq-3',
    buyer_org_id: 'buy-manipal',
    created_by: 'demo-user-3',
    title: 'Portable ultrasound + cardiac probe — 6 units',
    category_id: 1,
    description: 'Cardiology department portable ultrasound, must include phased array cardiac probe (P5-1 or equivalent). Demo unit at our Bengaluru flagship preferred before order.',
    target_specs: {},
    quantity: 6,
    target_unit_price_usd: 4500,
    required_lead_time_days: 45,
    required_certifications: ['CDSCO_IMPORT', 'NMPA'],
    incoterm: 'CIF',
    delivery_port: 'Bengaluru ICD',
    closes_at: '2026-06-20T00:00:00Z',
    status: 'open' as const,
    created_at: '2026-05-25T08:00:00Z',
  },
  {
    id: 'rfq-4',
    buyer_org_id: 'buy-medplus',
    created_by: 'demo-user-4',
    title: '50,000× 3-ply surgical masks (Type IIR)',
    category_id: 9,
    description: 'Standing-order pricing for monthly drawdown. CDSCO listed, BFE ≥98%, fluid-resistant.',
    target_specs: {},
    quantity: 50000,
    target_unit_price_usd: 4,
    required_lead_time_days: 14,
    required_certifications: ['CE'],
    incoterm: 'FOB',
    delivery_port: 'Hyderabad ICD',
    closes_at: '2026-06-08T00:00:00Z',
    status: 'open' as const,
    created_at: '2026-05-27T08:00:00Z',
  },
  {
    id: 'rfq-5',
    buyer_org_id: 'buy-apollo',
    created_by: 'demo-user-1',
    title: 'Hematology + Biochem combo for new lab in Hyderabad',
    category_id: 6,
    description: '5-part hematology + semi-auto biochemistry. AMC for 3 years quote separately. Reagent contracts negotiable.',
    target_specs: {},
    quantity: 2,
    target_unit_price_usd: 14000,
    required_lead_time_days: 50,
    required_certifications: ['CDSCO_IMPORT', 'NMPA', 'CE'],
    incoterm: 'CIF',
    delivery_port: 'Hyderabad ICD',
    closes_at: '2026-06-30T00:00:00Z',
    status: 'open' as const,
    created_at: '2026-05-28T08:00:00Z',
  },
];
